In [1]:
import numpy as np
import pandas as pd 
dataSet = pd.read_csv('ex1data2.txt', header=None, names=['Size', 'BedRooms', 'Price'])
dataSet = (dataSet - dataSet.mean()) / dataSet.std()
dataSet.head()

Size  BedRooms     Price
0  0.130010 -0.223675  0.475747
1 -0.504190 -0.223675 -0.084074
2  0.502476 -0.223675  0.228626
3 -0.735723 -1.537767 -0.867025
4  1.257476  1.090417  1.595389

In [2]:
dataSet.insert(0, 'theta0', 1)
dataSet.head()

theta0      Size  BedRooms     Price
0       1  0.130010 -0.223675  0.475747
1       1 -0.504190 -0.223675 -0.084074
2       1  0.502476 -0.223675  0.228626
3       1 -0.735723 -1.537767 -0.867025
4       1  1.257476  1.090417  1.595389

In [3]:
cols = dataSet.shape[1]
X = dataSet.iloc[:, :-1]
y = dataSet.iloc[:, cols-1:cols]
X.head()

theta0      Size  BedRooms
0       1  0.130010 -0.223675
1       1 -0.504190 -0.223675
2       1  0.502476 -0.223675
3       1 -0.735723 -1.537767
4       1  1.257476  1.090417

In [4]:
y.head()

Price
0  0.475747
1 -0.084074
2  0.228626
3 -0.867025
4  1.595389

In [5]:
X = np.matrix(X.values)
y = np.matrix(y.values)
'''
X1 = np.matrix(X)
y1 = np.matrix(y)
matrix([[-9.98551124e-17,  8.84042349e-01, -5.24551809e-02]])
X2 = np.matrix(X.values)
y2 = np.matrix(y.values)
matrix([[-1.10856950e-16,  8.84042349e-01, -5.24551809e-02]])
得到的结果不同
'''
theta = np.matrix(np.array([0, 0, 0]))
X.shape, y.shape, theta.shape

((47, 3), (47, 1), (1, 3))

In [6]:
def computeCost(X, y, theta):
    inner = X * theta.T
    cost = np.sum(inner) / (2 * len(X))
    return cost

In [7]:
def gradientDescent(X, y, theta, alpha, iters):
    parameters = int(theta.ravel().shape[1])
    temp = np.matrix(np.zeros(theta.shape))
    cost = np.zeros(iters)
    for i in range(iters):
        inner = X * theta.T - y
        for j in range(parameters):
            term = np.multiply(inner, X[:,j])
            temp[0,j] = temp[0,j] - alpha * np.sum(term) / len(X)
        theta = temp
        cost[i] = computeCost(X, y, theta)
    return theta, cost

In [11]:
alpha = 0.01
iters = 1500
theta1, cost = gradientDescent(X, y, theta, alpha, iters)
theta1 ,cost

(matrix([[-1.10916005e-16,  8.84039224e-01, -5.24520557e-02]]),
 array([-1.81526369e-20, -3.69090101e-20,  1.84545051e-19, ...,
        -5.78733279e-17, -5.19678863e-17, -2.95272081e-17]))

In [9]:
# 正规方程
def normalEqn(X, y):
    theta = np.linalg.inv(X.T@X)@X.T@y #X.T@X等价于X.T.dot(X)
    return theta

In [12]:
theta2 = normalEqn(X, y)
theta2

matrix([[-1.04083409e-16],
        [ 8.84765988e-01],
        [-5.31788197e-02]])

In [ ]:
#梯度下降得到的结果是matrix([[-1.10851045e-16,  8.84042349e-01, -5.24551809e-02]])
#正规方程得到的结果是matrix([[-1.04083409e-16], [ 8.84765988e-01], [-5.31788197e-02]])